export interface ICatalogItem {
    name: string,
    type: "Рулонні штори" | "Вертикальні жазюзі" | "Горизонтальні жазюзі" | "День-Ніч"
    isInStock: "available" | "not-available" | "little-in-stock", //В наявності
    isNew: boolean,
    isPromotion: boolean, //Акция
    fabricTexture: string, //Фактура ткании
    waterproofnessLevel: string, //Рівень водонепроникності
    collection: string,
    opacity: string,
    guarantee: string,
    composition: string, //Склад
    maxWidth: string,
    originCountry: string,
    availableColors: string[]
}

export type CatalogList = Array<ICatalogItem>

// Example list for rendering
export const catalogList: CatalogList = [
    {
        name: "Бірма біла",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_тканини_Бірма-біла.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Альмерія чорна",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Альмерія-чорна.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Арома бежева",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Арома_бежева.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Арома золота",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Арома-золота.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Бірма бежева",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Бірма_бежева.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Бірма біла",
        type: "Рулонні штори",
        isInStock: "little-in-stock",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_тканини_Бірма-біла.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Бірма сіра",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Бірма_сіра.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Бірма бежева",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Бірма_бежева.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Арома бежева",
        type: "Рулонні штори",
        isInStock: "not-available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Арома_бежева.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Бірма біла",
        type: "Рулонні штори",
        isInStock: "little-in-stock",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_тканини_Бірма-біла.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Бірма біла",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_тканини_Бірма-біла.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
    {
        name: "Бірма сіра",
        type: "Рулонні штори",
        isInStock: "available",
        isNew: true,
        isPromotion: true,
        fabricTexture: "Фактурна",
        waterproofnessLevel: "Фактурна",
        collection: "Бірма",
        opacity: "100%",
        guarantee: "1 рік",
        composition: "100% поліестер",
        maxWidth: "260 см",
        originCountry: "Китай",
        availableColors: ["/assets/images/Фото_Бірма_сіра.png", "/assets/images/Фото_Бірма-бежева.png", "/assets/images/Фото_Бірма-сіра.png", "/assets/images/Фото_Бірма-сіра(1).png"]
    },
]